### PR TITLE
github(auth): convert GET parameters to basic auth

### PR DESCRIPTION
**Pull request by derekschrock**
Due to deprecation of query parameters convert api.github.com access to
use Basic HTTP Authentication.

Also, don't need to recreate another LWP::UserAgent object.

### CODE REVIEW

**Comment by grembo** [comment]
See https://github.com/freebsd/portscout/pull/9

**Comment by derekschrock** [comment]
Ah.   Ok.  Didn't realize that was there.   Just started talking about this subject late last night on freenode#freebsd.

**Comment by koobs** [comment]
Thanks for your proactive help Derek :)

**Comment by grembo** [comment]
> Ah. Ok. Didn't realize that was there. Just started talking about this subject late last night on freenode#freebsd.

Was half asleep when I commented earlier today, also thanks from me for your help.

**Pull request closed without merging**
